---

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  react/jsx-filename-extension: 0
  eslint-disable react/jsx-props-no-spreading: 0